### ISSUE TITLE
Ошибка загрузки после первой стадии установки.

### ISSUE THREAD

**Issue by LeGeNdHeRooooo** [yakimka/Hackintosh-Dell-7577#1]
Сделал всё как в инструкции, то есть создал флешку пораскинул по нужным папкам kext'ы. 
Загружаюсь с флешки > очистил нужный диск для установки > ставлю на этот диск.
Дальше идёт перезагрузка > перехожу в one-time-boot > флешка > Install с диска на который ставлю MacOS > но потом вылетает окно с ошибкой.

Плюс, при первой загрузке при нажатии установки, образ вообще не хочет устанавливаться и приходиться прописывать: `date 041707482016`
То есть, ставить 2016 год чтобы пропусило в момент установки.
После первого "накатывания" с флешки на диск и при последующей установки возникает данная проблема.

**Лог прилагается:** https://github.com/LeGeNdHeRooooo/7577-MacIssue/blob/master/LogFromInstall

**Окно ошибки:**

![15871282107929133099634094883930](https://user-images.githubusercontent.com/19389665/79571583-9e4e0200-80e5-11ea-8083-0bd21c04349a.jpg)

**Comment by yakimka** [comment]
1. Файлы брал из раздела релизы или прям из репозитория?
2. Каким способом делал флешку?
3. Если делал загрузочную флешку не из MacOS то по какой ссылке качал образ?
4. Какую версию MacOS пытался поставить?
5. Выполнил ли действия из раздела [требования](https://github.com/yakimka/Hackintosh-Dell-7577#-%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)?
6. Какую версию Clover использовал?

**Comment by LeGeNdHeRooooo** [comment]
@yakimka 
1. С релиза.
2. Clover, по твоей инструкции и твоим ссылкам.
3. Качал по этой: https://mac-ru.net/viewtopic.php?t=1402
4. 10.14.6
5. На них и опирался.
6. Последнюю, что есть на SourceForge.

**Дополнение:**
У меня получилось установить, проблема была в том что установка была не полностью завершена и после перезагрузки ноутбук перезагружался не с флешки а с диска, что естественно выдавало Dell Support окно и программа пыталась восстановить и запустить систему.
Решение было в том чтобы в BIOS, сделать принудительно первой загрузку с флешки.

**Но, появилась новая проблема**:
Не понятно что делать с интернетом, то есть карта встроенная для Wi-Fi, не поддерживается, а через USB модуль не получается, он его вообще не видит.

**В итоге:*
Красивый MacOS, без интернета)

**Comment by yakimka** [comment]
Звук должен работать. Попробуй то что описано в ридми для таких случаев - [пропал звук или перестали работать некоторые кексты](https://github.com/yakimka/Hackintosh-Dell-7577#kexts-after-update)

WIFi карта, с которой поставляется ноутбук не поддерживается макосью. Макось также ужасно работает с usb-wifi картами.
Подключить интернет есть несколько вариантов:
1. Ethernet.
2. Заменить встроенный модуль на поддерживаемый.
3. Подключить интернет через Tethering режим Android (возможно с iOS тоже будет работать) телефона (для этого в сборке уже имеется HoRNDIS кекст).

**Comment by yakimka** [comment]
Я так понимаю проблема решена, поэтому закрываю issue. Если остались проблемы по другим вопросам - можешь открыть issue уже для них.

**Comment by LeGeNdHeRooooo** [comment]
Спасибо большое!
